export const DEFAULT_DOCUMENT_STORAGE_PROVIDER = "local";
export const DEFAULT_DOCUMENT_MAX_UPLOAD_BYTES = 25 * 1024 * 1024;
export const DOCUMENT_MAX_UPLOAD_BYTES_ENV = "DOCUMENT_MAX_UPLOAD_BYTES";
export const DOCUMENT_LOCAL_STORAGE_DIR_ENV = "DOCUMENTS_LOCAL_STORAGE_DIR";
export const DEFAULT_DOCUMENT_LOCAL_STORAGE_DIR = "uploads";
